name:                apply-unordered
version:             0.1.0
github:              "mgsloan/apply-experiments"
license:             BSD3
author:              "Michael Sloan"
maintainer:          "mgsloan@gmail.com"
copyright:           "2019 Michael Sloan"
synopsis:            Apply functions to arguments in an unordered type-directed fashion
category:            Functions

extra-source-files:
- changelog.md

description:         Please see the README on GitHub at <https://github.com/mgsloan/apply-experiments#readme>

dependencies:
- base >= 4.9 && < 5

default-extensions:
- DataKinds
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- ScopedTypeVariables
- TypeFamilies
- TypeOperators

library:
  source-dirs: src

tests:
  apply-unordered-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - apply-unordered
    - should-not-typecheck
    - hspec
